spring.application.name=hospital-records-scraper

spring.datasource.url=jdbc:postgresql://localhost:5432/hospital_records
spring.datasource.username=postgres
spring.datasource.password=Mayank@13579

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8081